server:
  port: 80

spring:
  application:
    name: alibaba-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 47.111.224.5:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

feign:
  sentinel:
    enabled: true
